- hosts: all
  become: true
  roles:
    - role: '../roles/locust'
  tasks:
    # Set myvar fact for every host in a play
    - set_fact:
        master_ip: "{{ hostvars['master']['ansible_default_ipv4']['address'] }}"
      delegate_to: "{{ item }}"
      with_items: "{{ play_hosts }}"
      run_once: yes
    - name: "Add Master to Hosts File"
      lineinfile: dest=/etc/hosts regexp='.*{{ master_ip }}$' line="{{ master_ip }} master" state=present
    - name: Run locust master in background
      shell: nohup locust --master </dev/null >/dev/null 2>&1 &
      args:
        chdir: /vagrant
      when: inventory_hostname == 'master'
    - name: Run locust slave in background
      shell: nohup locust --slave --master-host=master </dev/null >/dev/null 2>&1 &
      args:
        chdir: /vagrant
      when: inventory_hostname != 'master'